language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run flow
  - npm run test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  on: master
